name: Django

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: 3.7.7

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.7
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
